# -*- coding: utf-8 -*-
"""Sif2500014.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13rcDFJBkklOMEGvd4BE9sR6PCJZzQbCi
"""

print("welcome to quiz game")
name = input("enter your name:")
print("Hello",name)
print("Let s start the quiz!")

score=0

Q1=input("1. what is the capital of Sri Lanka?")

if Q1.lower() == "colombo":
  print("Correct")
  score = score+1
else:
  print("Wrong")

Q2=input("2. 150+170")

if Q2 =="270":
  print("Correct")
  score = score+1
else:
  print("Wrong")

Q3=input("3. what is the highest mountain in sri lanka")

if Q3.lower() == "piduruthalagala":
  print("Correct")
  score = score+1
else:
  print("Wrong")

print("Your score is:",score)

if score == 3:
  print("Excellent")
elif score == 2:
  print("Good job")
else:
  print("Try again")